### ISSUE TITLE
A change log for new versions

### ISSUE THREAD

**Issue by subsidel** [connected-web/product-monitor#13]
A change log for new versions would be useful, so users can quickly see what has changed when updating without having to check commit history :)

**Comment by Markavian** [comment]
Nice idea, where would you expect to find the change log?

**Comment by subsidel** [comment]
CHANGELOG 

http://keepachangelog.com/

**Comment by Markavian** [comment]
Sounds good, I'll do that.

**Comment by Markavian** [comment]
Done: https://github.com/johnbeech/product-monitor/blob/master/CHANGELOG.md
