### ISSUE TITLE
API page doesn't work if hosted on a different port then 8080

### ISSUE THREAD

**Issue by Markavian** [connected-web/product-monitor#14]
![screen shot 2015-06-15 at 09 45 18](https://cloud.githubusercontent.com/assets/1431385/8156251/489ef996-1343-11e5-84c7-debca2793bd5.png)

Need some sort of host/url detection to use the status-checker component with URLs local to the server. The component currently expects a fully formed data-url property.

**Comment by subsidel** [comment]
+1

**Comment by Markavian** [comment]
Will close this now, but need to verify using the Open Stack server instance which is running off port 80.
