### ISSUE TITLE
Component to check and notify if updated product-monitor server is available on NPM

### ISSUE THREAD

**Issue by Markavian** [connected-web/product-monitor#24]
Using the NPM api (https://docs.npmjs.com/api/npm) it should be possible to compare the local package.json against the public `product-monitor` NPM entry to see if an update is available.

It should also be possible to perform a local update to the server and restart, making sure users of product monitor get the latest features and can stay up to date.

**Comment by subsidel** [comment]
This feature should be opt-in.

**Comment by Markavian** [comment]
Will make sure that its opt-in - I was planning to have an icon button at the top right that appeared when a new version was available. I guess users could choose to dismiss this. I could also have a settings option to disable the feature.

**Comment by johnbeech** [comment]
This is what the feature looks like present when run directly from the product-monitor product:
![image](https://cloud.githubusercontent.com/assets/6341696/8640363/de4ed4d8-28ed-11e5-8768-20799ced0cc7.png)

Not tested it in a dependent project yet.

**Comment by johnbeech** [comment]
And this is what it looks like if you update in to the future...
![image](https://cloud.githubusercontent.com/assets/6341696/8640374/1d614340-28ee-11e5-803f-5e3981726c1b.png)

**Comment by Markavian** [comment]
Issue: this process takes several seconds on most machines, and hitting the endpoint before it has initially cached causes the process to fork. Suggest a fast fail return, with a cache managed by the endpoint.
