### ISSUE TITLE
Need detailed information for Status Checker buttons

### ISSUE THREAD

**Issue by johnbeech** [connected-web/product-monitor#37]
There is not enough information about the history of a status checker check, and the button just links through to the JSON response at the moment.

Ideally the button should link through to a detailed information page, with a "Retry" button that clears down the cached request and tries again.

**Comment by Markavian** [comment]
![image](https://cloud.githubusercontent.com/assets/1431385/8895308/76cccad2-33cd-11e5-9549-68a567b66ad0.png)
