### ISSUE TITLE
Remove error message from status-button to keep size consistent

### ISSUE THREAD

**Issue by Markavian** [connected-web/product-monitor#41]
With the additions of the sparkline graph and detailed status page; understanding the `<status-button>` component is much easier now, and no longer requires the extended message which causes layouts to break with the inconsistent width of the error message.

Removing the error message would keep the width of the component consistent, and make layout easier.

**Comment by johnbeech** [comment]
Tested fix: added `hidden` CSS class to this information.

``` html
<span class="hidden">{{latest.message}}</span>
```
