### ISSUE TITLE
Status Button / Status Checker should be more lenient towards `510 Request timed out` errors

### ISSUE THREAD

**Issue by Markavian** [connected-web/product-monitor#44]
The rapid timeout on requests (900ms) means that very frequently errors are displayed on the dashboard. In summary though, these can be discounted, unless a majority of the last 10 checks have failed in this way.

The report status colour could definitely be improved by a bit of fuzzy / intelligent matching.

**Comment by johnbeech** [comment]
Have increased the default timeout to 1500ms.
