### ISSUE TITLE
Server status component

### ISSUE THREAD

**Issue by johnbeech** [connected-web/product-monitor#5]
Feature: a standard component that monitors the health of the server, so that if the client loses connection with the server a message can be displayed on the client, and perhaps normal polling operations can be halted.

**Comment by subsidel** [comment]
Self monitoring monitor?
Suggestion: when a 404 is returned from a poll request, change to a warning colour (yellow type deal) and halt polling, adding a button to restart polling from that component.

**Comment by Markavian** [comment]
Yellow is a good suggestion, not so keen on requiring user interaction to restart a component though - I'm imagining the monitor being run on a Pi or some other maybe-not-so-easily-accessible computer.

**Comment by subsidel** [comment]
I should say optional button, so limit the rate a which it polls to a much longer time, and a user can choose to "prematurely poll" if they wanted. For example if someone knows that the server will be back up before the longer poll time.

**Comment by Markavian** [comment]
That makes sense, it could have a long poll of say 5 or 10 minutes, and a manual "Retry now!" button.

**Comment by subsidel** [comment]
dangerious_premature_reenable_poll_buttons ?

**Comment by Markavian** [comment]
Added in master.

Big and bulky at the top of the page, can be closed, but pops back in when it hits its refresh timer.
