### ISSUE TITLE
Apicache depdency raises lodash@1.3. deprecation warning

### ISSUE THREAD

**Issue by Markavian** [connected-web/product-monitor#51]
See: https://github.com/kwhitley/apicache/issues/18

When using `npm install` to install product monitor, the following warning is generated:
`npm WARN deprecated lodash@1.3.1: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0`

**Comment by johnbeech** [comment]
Don't think this is an issue any more.
