### ISSUE TITLE
Template file not found: C:\Temp\tester/config/templates/page-template.html. If this is your server, please create this file. Error: ENOENT: no such file or directory, open 'C:\Temp\tester\config\templates\page-template.html'

### ISSUE THREAD

**Issue by rdehuyss** [connected-web/product-monitor#56]
Hi,

I followed the tutorial (twice) and I receive the following error...

Template file not found: C:\Temp\tester/config/templates/page-template.html. If this is your server, please create this file. Error: ENOENT: no such file or directory, open 'C:\Temp\tester\config\templates\page-template.html'

Environment:

- windows 10
tried with both
- npm 3.10.10 and 5.6.0
- node 6.x and 9.4.0

If I go to the provided urls on disk, I see no files so the error message is correct.

What am I doing wrong?

**Comment by johnbeech** [comment]
Hey, product monitor was originally written with support for node 0.12, and then upgraded to work with 4~, but it expects files to be in certain places based on the node_modules folder, which has changed with newer versions of node.

I'll have a look this evening to reproduce your problem, and then I should be able to get a fix out for you... watch this space :)

**Comment by rdehuyss** [comment]
You are a Hero!

**Comment by johnbeech** [comment]
@rdehuyss I've published version 2.3.3 to npm, my in house tester confirms that first time installation should work as intended now. Try running again from the README, I've updated the steps slightly, see:
https://github.com/connected-web/product-monitor/

Let me know if you're still having problems.

**Comment by rdehuyss** [comment]
Thx! Works as expected now...
