### ISSUE TITLE
Client auto-update

### ISSUE THREAD

**Issue by johnbeech** [connected-web/product-monitor#6]
Feature: if the server is restarted, either because of maintenance, or to support a new version of the monitor, the client should do a full page refresh to retrieve new components. This could be achieved through a similar mechanism to the server status component idea.

**Comment by subsidel** [comment]
How should the client know that the server was restarted? By calling home on itself with some version information and checking if the server is newer?

**Comment by Markavian** [comment]
My idea was to have the server generate a version/timestamp/hash at start up which it gives to the client - when the client checks the status of the server, if that hash value has changed then the client knows its talking to a different instance of the server.

**Comment by subsidel** [comment]
Could be useful for a "pi strapped to a tv on a wall" type monitor

**Comment by Markavian** [comment]
All shiny, of of 1.2.0 release, server can be restarted, and the client healthily realises this and restarts itself. Other components still continue to flail helplessly however. Should provide fallback against network drops at least.

**Comment by Markavian** [comment]
Good for upgrading the server as well *, which is happening quite a bit in development at the moment.
