### ISSUE TITLE
Custom-page-template support

### ISSUE THREAD

**Issue by johnbeech** [connected-web/product-monitor#7]
Currently the only page template available is Bootstrap.

Provide a way to select a different page template (via a URL naming scheme?) and have each component define a default template, as well as framework specific templates, such as Bootstrap, Semantic UI, Angular, "Dashboard Style", etc.

**Comment by subsidel** [comment]
DA'ing a bit, but what function would this server, what benefit does this add?

Edit: I was distracted when I was typing this >>

**Comment by Markavian** [comment]
I'm forward identifying some reuse in the components - there's client side logic that says "get data, and draw it like X", but X is specific to the component. What if someone wants to render X in a different way, but keep the same logic. E.g. the status component at the moment is this big broad wide thing, with a visible URL, when maybe just a green box with a label in it would be ok.

Also, I wanted to try out Semantic UI components without throwing away the Bootstrap stuff.

**Comment by subsidel** [comment]
Fair enough

**Comment by Markavian** [comment]
Updated issue name: currently the only page template supported is boot-strap, other layout frameworks or stylesheets, or themes... should be easy to configure by anyone using the server.

**Comment by johnbeech** [comment]
After some more discussion, this sounds like plugin territory. There should be a default-route plugin, which would direct users to the "management console" by default, and could be configured, via content plugins to direct users towards other routes hosted by the server.

**Comment by johnbeech** [comment]
I think the solution to this is to copy the `/monitor/templates/page-template.html` file into the `user-content` directory so that people can edit this file to their hearts content.

**Comment by johnbeech** [comment]
Implemented in version 2.0.3.
